FROM rust:1.72-bookworm as builder

WORKDIR /app/rinha-luajit-rs
COPY . .
RUN cargo install --path .


FROM debian:bookworm-slim

COPY --from=builder /usr/local/cargo/bin/meta-rinha /usr/local/bin/meta-rinha

ENTRYPOINT ["meta-rinha", "/var/rinha/source.rinha.json"]
