FROM rust:1.72-bookworm as builder
RUN cargo install rinha
FROM debian:bookworm-slim

COPY --from=builder /usr/local/cargo/bin/rinha /usr/local/bin/rinha

ENTRYPOINT ["rinha", "/var/rinha/source.rinha"]
